PEXPORTS=pexports
PDCURSES_DIR=pdcurses
PDCURSESW32_DIR=pdcurses-win32a
PDCURSESDLL=$(PDCURSES_DIR)/pdcurses.dll
PDCURSESDEF=$(PDCURSES_DIR)/pdcurses.def
PDCURSESLIB=$(PDCURSES_DIR)/pdcurses.lib
PDCURSESW32DLL=$(PDCURSESW32_DIR)/pdcurses.dll
PDCURSESW32DEF=$(PDCURSESW32_DIR)/pdcurses.def
PDCURSESW32LIB=$(PDCURSESW32_DIR)/pdcurses.lib
SED=sed
DLLTOOL=dlltool
RM=rm
CP=cp
MKDIR=mkdir
GEN_DIR=gen
BUILD=build
PDCURSES_BUILD=$(PDCURSES_DIR)/build
PDCURSESW32_BUILD=$(PDCURSESW32_DIR)/build
SETUP_TEMPLATE=setup.py_template

$(PDCURSESW32_DIR):
	$(MKDIR) $(PDCURSEW32_DIR)

$(PDCURSESW_DIR):
	$(MKDIR) $(PDCURSEW_DIR)

$(PDCURSESDEF):
	$(PEXPORTS) $(PDCURSESDLL) | $(SED) -e "s/^_//g" > $(PDCURSESDEF)

$(PDCURSESLIB): $(PDCURSESDEF)
	$(DLLTOOL) --dllname $(PDCURSESDLL) --def $(PDCURSESDEF) --output-lib $(PDCURSESLIB)

$(PDCURSES32DEF):
	$(PEXPORTS) $(PDCURSES32DLL) | $(SED) -e "s/^_//g" > $(PDCURSES32DEF)

$(PDCURSES32LIB): $(PDCURSES32DEF)
	$(DLLTOOL) --dllname $(PDCURSES32DLL) --def $(PDCURSES32DEF) --output-lib $(PDCURSES32LIB)

pdcurses-setup.py:
	$(CP) $(SETUP_TEMPLATE) $(PDCURSES_DIR)/setup.py
	$(SED) -i -e s/PDCURSES_FLAV// $(PDCURSES_DIR)/setup.py

pdcurses-win32a-setup.py:
	$(CP) $(SETUP_TEMPLATE) $(PDCURSESW32_DIR)/setup.py
	$(SED) -i -e s/PDCURSES_FLAV/_WIN32A/ $(PDCURSESW32_DIR)/setup.py

defs: $(PDCURSESDEF) $(PDCURSESW32DEF)

libs: $(PDCURSESLIB) $(PDCURSESW32LIB)

gen: defs libs

all: gen pdcurses-setup.py pdcurses-win32a-setup.py

clean:
	$(RM) -f $(PDCURSESDEF) $(PDCURSESLIB)
	$(RM) -f $(PDCURSESW32DEF) $(PDCURSESW32LIB)
	$(RM) -rf $(BUILD) $(PDCURSES_BUILD) $(PDCURSESW32_BUILD)
